const users = [
    {
        id: 11,
        firstName: "Monica",
        lastName: "Geller",
        email: "monica@example.com",
        password: "123mm",
        age: "29",
        city: "New York",
    },
    {
        id: 22,
        firstName: "Joey",
        lastName: "Tribiani",
        email: "joey@example.com",
        password: "1111",
        age: "31",
        city: "Chicago",
    },
    {
        id: 33,
        firstName: "Rachel",
        lastName: "Green",
        email: "rachel@example.com",
        password: "123rr",
        age: "30",
        city: "New York",
    },
    {
        id: 44,
        firstName: "Phoebe",
        lastName: "Buffay",
        email: "phoebe@example.com",
        password: "princessConsuela",
        age: "31",
        city: "Chicago",
    },
    {
        id: 55,
        firstName: "Chandler",
        lastName: "Bing",
        email: "chandler@example.com",
        password: "123cc",
        age: "29",
        city: "LA",
    },
    {
        id: 66,
        firstName: "Ross",
        lastName: "Geller",
        email: "ross@example.com",
        password: "123rr",
        age: "30",
        city: "San Diego",
    },
    {
        id: 77,
        firstName: "Gunther",
        lastName: "Geller",
        email: "gunther@example.com",
        password: "123gg",
        age: "28",
        city: "San Diego",
    },
];

module.exports = users;